[package]
name = "tetris"
version = "0.1.0"
authors = ["aita <792803+aita@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version = "0.35.1", features = ["ttf"]}
rand = "0.8.4"
